### ISSUE TITLE
Hi, would you please output some information about total build time?

### ISSUE THREAD

**Issue by Zhao-Michael** [thomasthiry/vsbuildtimereport#1]
Some projects are very big, you know, so, the compile time is very long... Maybe it will help if you output complie time after solution compile is down

**Comment by thomasthiry** [comment]
I'm not sure I get your point. You can open the window to see the summary of all compile times, including the one that was just run. Is that what you're looking for?

**Comment by Zhao-Michael** [comment]
Emmm... I mean, in the Output Window, output from Build, VS always writes some information in that window when building, maybe you can also write the compile time in there. ths!

**Comment by thomasthiry** [comment]
That's a nice idea actually. :-)
I'm not working on this extension right now, but I'll keep the idea for
when I work on this again!

Thanks for sharing it!
